# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=25, null=True)),
                ('label', models.CharField(choices=[('Fitness', 'Fitness'), ('Diet', 'Diet'), ('Creed', 'Creed')], default='Fitness', max_length=3)),
                ('content', models.TextField()),
            ],
        ),
    ]
